name: Prerequisite

on:
  push:
  workflow_dispatch:

jobs:
  prerequisite-job:
    runs-on: ubuntu-latest

    steps:
      - name: Prerequisite Step
        run: echo "This is a prerequisite step."
